# Generated by Django 4.0.8 on 2022-12-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbComment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('writedat', models.DateTimeField(blank=True, db_column='WritedAt', null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
            ],
            options={
                'db_table': 'tb_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDomain',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tb_domain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNews',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('maincategory', models.CharField(blank=True, db_column='MainCategory', max_length=16, null=True)),
                ('subcategory', models.CharField(blank=True, db_column='SubCategory', max_length=16, null=True)),
                ('writedat', models.DateTimeField(blank=True, db_column='WritedAt', null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=128, null=True)),
                ('content', models.TextField(db_column='Content')),
                ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True)),
                ('photourl', models.TextField(blank=True, db_column='PhotoURL', null=True)),
                ('writer', models.CharField(blank=True, db_column='Writer', max_length=16, null=True)),
                ('stickers', models.TextField(blank=True, db_column='Stickers', null=True)),
                ('press', models.CharField(blank=True, db_column='Press', max_length=16, null=True)),
            ],
            options={
                'db_table': 'tb_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, db_column='UserID', max_length=16, null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=32, null=True)),
            ],
            options={
                'db_table': 'tb_user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
